### ISSUE TITLE
Feature Request: Clicking site thumbnail should open site

### ISSUE THREAD

**Issue by matt-west** [Automattic/studio#103]
### What

Clicking on the site thumbnail on the Overview tab should open the site.

### Why

This feels like a natural place to launch the site.

### How

We may want to add a hover state to the thumbnail to explain what will happen when you click it.

**Comment by enamul-hoque** [comment]
Also, when the Server is stopped.
- Clicking on the 'Thumbnail' should start the Server. or, an Indicator of some sort.

![image](https://github.com/Automattic/studio/assets/48347338/4fb23b01-fd75-46e3-be74-5cfd79aab033)

**Comment by faisalahammad** [comment]
+1

**Comment by matt-west** [comment]
@wojtekn Let's add a hover state to the thumbnail to communicate that clicking it will open the site. 

The border color should change to blueberry and a 90% white overlay should be applied on top of the thumbnail image.

![Image](https://github.com/Automattic/studio/assets/417538/4cbd065f-362e-4bff-a965-1e3e20830be1)

| Default | Hover | Focus |
|--------|--------|--------|
| ![image](https://github.com/Automattic/studio/assets/417538/108b9afd-ce66-41fb-9c2e-6cb60a7b8f08) | ![image](https://github.com/Automattic/studio/assets/417538/090735fe-1585-492f-a66b-41e4257c14f0) | ![image](https://github.com/Automattic/studio/assets/417538/29b41902-e61b-47be-b654-1c03ab76f8ba) |
