### ISSUE TITLE
Unable to load a font file

### ISSUE THREAD

**Issue by alaczek** [Automattic/studio#110]
### Quick summary

I was not able to add a font via WordPress Font Library - the font file was stuck loading with no error messages.

### Steps to reproduce

1. Start the Studio app, and create or start an existing site.
2. With a block theme active (Assembler for me) open up the site editor and go to Global Styles.
3. Click on Typography and then Manage Fonts icon.
<img width="766" alt="image" src="https://github.com/Automattic/studio/assets/4550351/256f01f4-e189-4f09-bef1-414d98e575a0">

4. Switch to Upload tab and drag & drop any .ttf font file.
<img width="1520" alt="image" src="https://github.com/Automattic/studio/assets/4550351/da964dcf-bdea-43a6-8afd-58a1bdb42e8d">

5. The file never finishes loading, although there are no errors. 

### What you expected to happen

I expected the font file to load properly.

### What actually happened

The file never finishes loading, although there are no errors or messages.

### Impact

One

### Available workarounds?

No but the app is still usable

### Platform

Mac Silicon

### Logs or notes

Browser: FF 125.0.1
<img width="287" alt="image" src="https://github.com/Automattic/studio/assets/4550351/93868bcb-5be9-483c-a1af-f3b7ecead66f">

(a side note and very minor but could we clean up the version number ^ ?)

**Comment by derekblank** [comment]
> (a side note and very minor but could we clean up the version number ^ ?)

I've also noted this, I believe it comes from this line where the package version and commit is combined into `devVersion`:

https://github.com/Automattic/studio/blob/3600d89faecec4c9c81d1970e2bafd7418ef78f0/scripts/prepare-dev-build-version.mjs#L24

I agree it's minor, but maybe we could use the short SHA instead of the full SHA-1 hash, e.g., `1.0.1-dev.6088e3da`. Also, probably no need to duplicate displaying the same version number twice in the system dialog, too.

**Comment by wojtekn** [comment]
@alaczek  @derekblank, note that it was a dev build, so it should be okay to have the whole hash there. The release build looks much cleaner, e.g.:

<img width="396" alt="Screenshot 2024-05-10 at 11 59 42" src="https://github.com/Automattic/studio/assets/727413/14d3d79c-74f5-4301-859d-6b3113bdd9c8">

**Comment by derekblank** [comment]
I investigated the actual font issue, and was able to replicate the testing steps. When uploading a font via Global Styles, the upload request just hangs indefinitely. 

I traced the request to the vendor/wp-now version of encodeAsMultipart here:

https://github.com/Automattic/studio/blob/6619e75c96a4ac47ff8fa6727f205c8823d1ca2a/vendor/wp-now/src/start-server.ts#L65-L71

When logging out the values, the request headers appear to be `null`. This may be related to updates to [vendor/wp-now/encode-as-multipart.ts](https://github.com/Automattic/studio/blob/trunk/vendor/wp-now/src/encode-as-multipart.ts), and possibly related to this commit where file uploads were updated to conform to the new server request format.

I'll continue to investigate, but just leaving these findings in case others have thoughts or further context.

**Comment by wojtekn** [comment]
Thanks for checking it @derekblank. It seems it can be fixed by https://github.com/Automattic/studio/pull/115.

**Comment by derekblank** [comment]
> Thanks for checking it @derekblank. It seems it can be fixed by #115.

Yep, confirming that applying the fix from #115 allows the request to succeed, and the font is uploaded successfully. 

https://github.com/Automattic/studio/assets/643285/29c872e2-f4d9-4a33-83e8-60c1cdfc08bd
