### ISSUE TITLE
Studio Wordpress isn't using the PHP version I have installed on my machine . . .

### ISSUE THREAD

**Issue by listeningGlass** [Automattic/studio#118]
The Studio version of Wordpress says that I'm running PHP 8.0.30-Dev but I have 8.3.6 installed on my mac. How can I get Studio Wordpress to use what I have installed? I tried creating a PHP.INI file and putting it in WP-ADMIN but no joy. Any ideas would be appreciated :-)

**Comment by wojtekn** [comment]
Thanks for reporting this @listeningGlass .

As we have the version selection tracked under https://github.com/Automattic/studio/issues/32, I will close this issue.
