### ISSUE TITLE
Feature Request: Option to update WordPress Core from Site Settings page

### ISSUE THREAD

**Issue by faisalahammad** [Automattic/studio#159]
### What

When we visit the Settings page, we can see the site details. However, if a WordPress update is available on the site, it does not display next to the "WP Version" option for updating from the Studio app. This feature should be added so that websites can be updated easily without logging in to the dashboard.

**Screenshot:**

![CleanShot 2024-05-24 at 01 50 48@2x](https://github.com/Automattic/studio/assets/13257516/6abc24b6-9e3a-4a79-afc5-0f26cf9560af)

### Why

It'll help to update WP Core faster and also make a cache so it can be use next time to update or upgrade another website core without manually download/update everytime from the dashboard.

**Comment by danielbachhuber** [comment]
This is a neat idea! Thanks for the suggestion 😊

**Comment by wojtekn** [comment]
This is a great idea!

We have it tracked under another issue: https://github.com/Automattic/studio/issues/84, so I will close this one.
