### ISSUE TITLE
Divi causes error upon upgrade

### ISSUE THREAD

**Issue by crobertwatson** [Automattic/studio#169]
### Quick summary

I tried installing Divi on WordPress Studio. At first, it installs fine. But when I upgrade it to the latest version, I get the error:

`Update failed: There has been a critical error on this website. Please check your site admin email inbox for instructions.Learn more about troubleshooting WordPress.`

and then Divi disappears from the Studio instance on localhost.

### Steps to reproduce

1. Start Studio app
2. Install Divi.zip as a theme using Appearance > Themes > Add New Theme and activate it.
[Uploading Divi.zip…]()
3. Go to Divi > Theme Options > Updates
4. Enter a valid username and ElegantThemes API key and click Save Changes
5. Go to Appearance > Themes and click "Update now" on the Divi theme to update the Divi theme.

### What you expected to happen

I expected the theme to update.

### What actually happened

Clicking Update now results in the error message 

`Update failed: There has been a critical error on this website. Please check your site admin email inbox for instructions.Learn more about troubleshooting WordPress.`

Upon refreshing Appearance > Themes, Divi disappears from the list of available themes.

Trying to reinstall Divi results in the following error:

`Unpacking the package…

Installing the theme…

The destination directory already exists and could not be removed.

Theme installation failed.`

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

### Logs or notes

`
### wp-core ###

version: 6.5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: undefined
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Twenty Twenty-Four (twentytwentyfour)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates
theme_path: /var/www/html/wp-content/themes/twentytwentyfour
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-Three: version: 1.4, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.7, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (6) ###

0-32bit-integer-warnings.php: author: (undefined), version: (undefined)
0-allowed-redirect-hosts.php: author: (undefined), version: (undefined)
0-check-theme-availability.php: author: (undefined), version: (undefined)
0-dns-functions.php: author: (undefined), version: (undefined)
0-sqlite.php: author: (undefined), version: (undefined)
0-thumbnails.php: author: (undefined), version: (undefined)

### wp-plugins-inactive (2) ###

Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 2000M
upload_max_filesize: 2000M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, PNG, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Emscripten 3.1.43 wasm32
httpd_software: PHP.wasm
php_version: 8.0.30-dev
php_sapi: wasm
max_input_variables: 1000
time_limit: 0
memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2000M
php_post_max_size: 2000M
curl_version: not available
suhosin: false
imagick_availability: false
pretty_permalinks: false
current: 2024-05-24T21:35:04+00:00
utc-time: Friday, 24-May-24 21:35:04 UTC
server-time: 2024-05-24T21:35:03+00:00

### wp-database ###

db_engine: SQLite
database_version: 3.40.1
database_size: 1 MB

### wp-constants ###

WP_HOME: http://localhost:8881
WP_SITEURL: http://localhost:8881
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined
DB_ENGINE: sqlite

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

**Comment by faisalahammad** [comment]
You should not share your Elegant Themes **username** and **API key**. Someone could misuse them, and your account could be suspended. Please remove both from above. Thank you.

**Comment by crobertwatson** [comment]
It’s just a test API key that I’ll be deleting once troubleshooting is done. It will be useless to anyone after that.

**Comment by wojtekn** [comment]
Hi @crobertwatson ! Thanks for reporting the issue and providing detailed information about the steps and your setup.

This issue is likely fixed in https://github.com/Automattic/studio/issues/100. Would you like to test it using the latest beta version? The build is available for [Mac Intel](https://href.li/?https://cdn.a8c-ci.services/studio/studio-darwin-x64-v1.0.3-beta2.app.zip), [Mac Apple Silicon](https://href.li/?https://cdn.a8c-ci.services/studio/studio-darwin-arm64-v1.0.3-beta2.app.zip) and [Windows](https://href.li/?https://cdn.a8c-ci.services/studio/studio-win32-v1.0.3-beta2.exe). Note that this version has not been fully tested yet.

**Comment by crobertwatson** [comment]
Looks like that resolved the issue. Thanks!
