### ISSUE TITLE
Sites directory is not removed from disk space

### ISSUE THREAD

**Issue by GearWestX** [Automattic/studio#223]
### Quick summary

After you delete a site from the Studio Dashboard, it will not be deleted from the Windows directory.

### Steps to reproduce

1. Start the Studio App.
2. Delete a site / all sites from the dashboard.
3. Creating a new first site with the first screen that you see after Studio has been recently installed on the machine.
4. Select the directory where to install the new site (There you can see the old deleted sites: )

![bug-deleted-sites](https://github.com/Automattic/studio/assets/48167278/9e601f7d-5723-4112-9824-ebb744184a84)

5. Search for the directories and files in my disk space.

![found-sites](https://github.com/Automattic/studio/assets/48167278/0689350f-cecb-4fca-bdcc-bbfac37703f5)

### What you expected to happen

The site directory and files should be removed from the Windows space; Otherwise, users' disk space will be loaded.

### What actually happened

The deleted site directory remains in the disk space but not in the Studio Dashboard:

![new-site-scratch](https://github.com/Automattic/studio/assets/48167278/9775ea24-b5c3-436c-900b-3a5603c1114d)

![found-sites](https://github.com/Automattic/studio/assets/48167278/b18d81e8-af80-454f-89cc-aec6dc51a1ad)

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform

Windows

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Mac

📌 FINDINGS/SCREENSHOTS/VIDEO
While the original report is from the Windows version, I was able to reproduce on the Mac version:

![CleanShot 2024-06-10 at 15 45 17@2x](https://github.com/Automattic/studio/assets/14153300/ae800c01-a722-4b47-a757-eef54dad1fec)

Above, you can see I only have 2 Studio sites, but the Studio folder shows 3 deleted sites. I expect the files would be removed if I deleted the sites.

📌 ACTIONS
- Triaged

**Comment by wojtekn** [comment]
@GearWestX @liviopv I tried on both Windows and Mac, and the directory was removed in both cases. Did you check the 'Delete site files from my computer' when you tried to delete the site?

![Screenshot 2024-06-10 at 17 00 10](https://github.com/Automattic/studio/assets/727413/b7533757-e77d-4ffb-a3ef-e0021aec17a6)

![Screenshot 2024-06-10 170213](https://github.com/Automattic/studio/assets/727413/e375fc42-02da-4d1c-8d2a-7b99f312ef10)

**Comment by liviopv** [comment]
Thanks @wojtekn! I missed it - can we make the checkbox more visually distinguishable?

I deleted another site and the files were removed. What about you @GearWestX?

**Comment by wojtekn** [comment]
> Thanks @wojtekn! I missed it - can we make the checkbox more visually distinguishable?

Thanks for confirming that. This window is a default system window, so I think we don't have the ability to change what this checkbox looks like.

**Comment by GearWestX** [comment]
@liviopv   I completely missed that too. 

It would be very helpful to have a second Windows pop-up that asks if the user wants to delete the site from the dashboard only or from the computer as well, just to make sure that users don't miss that.

Thanks @wojtekn  for the help :)
