### ISSUE TITLE
firefox - longtime reloads

### ISSUE THREAD

**Issue by wireinet** [Automattic/studio#234]
### Quick summary

In chrom - ok, firefox - from 10 to about 30 seconds to reload page in http://localhost:8881/

### Steps to reproduce

1)  start site, oopen in default browser (in my case - firefox)
2) update code, switch browser and hit f5 to reload page with my changes in code
3) long time wait for cdn.jsdelivr.net

### What you expected to happen

fast reload in firefox

### What actually happened

slow reload in firefox

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Windows

**Comment by wireinet** [comment]
Apdated. Today in chrom is exactly the same. LONG time reloads!!

**Comment by wojtekn** [comment]
@wireinet thanks for reporting the issue. Would you mind sharing more details about the site: is it a default empty site, or does it have any plugins, themes or custom code?

**Comment by wireinet** [comment]
Hello!
Its new site, bd is almost empty, no-plugins, simple start developing.
maybe it's my personal problem with firewall, but i switched it off, maybe antivir (also disable, bu how knows how this work, i dont delete it) what exactly cdn.jsdelivr.net? wordpress-studio use this to work? If not, that's ok - my problem, if yes, hm..need to dig deeper

**Comment by wojtekn** [comment]
Thanks @wireinet.

It seems `cdn.jsdelivr.net` is a CDN used by WordPress core to load some libraries, e.g., for emoji and media handling. Could you please check what exact URL is loaded in your case?

**Comment by wireinet** [comment]
Today i realized, that is not wordpress-studio issues. Its more global problem. That i not expect.
In live project is exactly the same!
Today it took more about 3 minuts!!!

![2024-06-17_23-27-02](https://github.com/Automattic/studio/assets/23517333/a940fdfe-c040-4701-98d5-22cbb7594604)

**Comment by wojtekn** [comment]
@wireinet, would you mind sharing the exact URL that is loaded slowly in your case?

**Comment by peterschimke** [comment]
@wojtekn does this problem still persist?

**Comment by wojtekn** [comment]
@peterschimke I couldn't reproduce an issue caused by slowly loading resources from the `cdn.jsdelivr.net` URL.
