### ISSUE TITLE
Feature Request: Language Switcher

### ISSUE THREAD

**Issue by stevehenty** [Automattic/studio#25]
### What

I would like to be able to switch the language used in the UI.

### Why

The automatic language detection seems to be based on the location. I'm in Spain so it's automatically set to Spanish but my OS and all my software is in English. That detection could be improved but it would also be great to be able to switch the language.

**Comment by yglik** [comment]
i also experience this issue, 
i am in israel and i use english all over but wordpress.com products are hebrew even though my profile settings is set to english.

and it apear to be wordpress.com-wide issue, not just the new studio.
for example, i see wordpress.com prices in ILS ₪ and noty dollars as i would expect

a fix would realy be appreciated, or direction on hoe to fix it

**Comment by zdenys** [comment]
> I would like to be able to switch the language used in the UI.

I agree that this is a nice feature.

> The automatic language detection seems to be based on the location. I'm in Spain so it's automatically set to Spanish but my OS and all my software is in English.

It would be best for the language to match the OS one by default. Relying on location is not optimal for various reasons.  cc: @Automattic/yolo @Automattic/sparrow

**Comment by wojtekn** [comment]
> It would be best for the language to match the OS one by default. Relying on location is not optimal for various reasons

It doesn't really rely on location, but I agree there is room for improvement here.

**Comment by gmovr** [comment]
Related: Automattic/dotcom-forge#6698

```sh
❯ defaults read -g AppleLanguages
(
    "en-ES",
    "es-ES"
)
```

```log
[2024-04-24T13:44:40.083Z][info][main] System locale: en-ES
[2024-04-24T13:44:40.083Z][info][main] Preferred languages: en-ES,es-ES
[2024-04-24T13:44:40.088Z][info][main] Used language: es
```

**Comment by pauloeaquino** [comment]
> I would like to be able to switch the language used in the UI.

I would love this feature as well. 

I'm based in Japan, but my primary language and OS settings are all in English. The Studio app is displaying the interface in Japanese and while I can manage my way, it's not my preferred/ideal language to navigate the app in.

**Comment by wojtekn** [comment]
As a workaround, does setting custom language in Mac **Settings -> Language & Region** work for you @pauloeaquino @stevehenty  @yglik ?

![Screenshot 2024-04-25 at 15 18 11](https://github.com/Automattic/studio/assets/727413/3b4aa29b-46c4-41a2-9905-d44edaeda623)

![Screenshot 2024-04-25 at 15 18 19](https://github.com/Automattic/studio/assets/727413/be8b573d-455d-4273-b594-2d4f6eb3ec79)

![Screenshot 2024-04-25 at 15 20 29](https://github.com/Automattic/studio/assets/727413/88829330-6a16-482f-a02f-24fddf57b9c5)

**Comment by zdenys** [comment]
> i see wordpress.com prices in ILS ₪ and noty dollars as i would expect

@yglik Each WordPress.com account has a specific currency set for it https://wordpress.com/support/payment/#default-currency

If you want to change it to USD from ILS, you can get in touch with Happiness Engineers at https://wordpress.com/help/

**Comment by fluiddot** [comment]
> Related: https://github.com/Automattic/dotcom-forge/issues/6698
> 
> ```shell
> ❯ defaults read -g AppleLanguages
> (
>     "en-ES",
>     "es-ES"
> )
> ```
> 
> ```
> [2024-04-24T13:44:40.083Z][info][main] System locale: en-ES
> [2024-04-24T13:44:40.083Z][info][main] Preferred languages: en-ES,es-ES
> [2024-04-24T13:44:40.088Z][info][main] Used language: es
> ```

This is likely the case shared in the above comments. The app tries to match based on the OS' preferred languages the locales supported in the app. Since `en-ES` doesn't find a match, it goes to the second item `es-ES` which results in picking Spanish.

I tested with different locales in the library we use ([`@formatjs/intl-localematcher`](https://formatjs.io/docs/polyfills/intl-localematcher/)) and for `en-ES`, it only resolves to `en-GB` 🤔.

**Results:**

```
match(
  ['en-ES', 'es-ES'], // requestedLocales
  ['es', 'en'], // availableLocales
  'en' // defaultLocale
);
// Result: es
```

```
match(
  ['en-ES', 'es-ES'], // requestedLocales
  ['es', 'en', 'en-GB', 'en-US'], // availableLocales
  'en' // defaultLocale
);
// Result: en-GB
```

**Comment by pauloeaquino** [comment]
> As a workaround, does setting custom language in Mac **Settings -> Language & Region** work for you @pauloeaquino @stevehenty @yglik ?

@wojtekn Setting a custom language in the Applications language setting did not seem to work for me. The Studio UI still displays in Japanese even if a custom language is added and set to English.
![fZXOFzB8FFzXeZm9bDWaTfdNOSvvzVwQXPQxEgga](https://github.com/Automattic/studio/assets/11362923/0901306a-a39f-4578-a3b4-3293e7976d16)
![cIAxfXkv5iIypV4dP1328PeDp7Nxk15XAJWfCZHR](https://github.com/Automattic/studio/assets/11362923/509f0e4c-6d8c-4faa-ad6b-315fa397fed3)

**Comment by fluiddot** [comment]
> @wojtekn Setting a custom language in the Applications language setting did not seem to work for me. The Studio UI still displays in Japanese even if a custom language is added and set to English.

This seems a similar case to the one I shared in https://github.com/Automattic/studio/issues/25#issuecomment-2077415345 related to using the English language with Spain as the region. The app doesn't match a supported language for locale `en-JA` and uses the next preferred language `ja` (Japanese).

We could try to explore how to extract the region from the preferred languages provided by the OS to address the issue. Although, it might be a bit tricky as some locales need the region to pick the right language.

**Comment by pauloeaquino** [comment]
> Setting a custom language in the Applications language setting did not seem to work for me. The Studio UI still displays in Japanese even if a custom language is added and set to English.

Update to my previous comment — setting the custom language setting to `English (UK) - English (UK)` worked. 

![CleanShot 2024-04-26 at 17 05 05@2x](https://github.com/Automattic/studio/assets/11362923/d44c2661-8a6c-4cdc-aac7-33cd53f1bb9f)

One thing I might add though is that there was was a prompt to "Relaunch" the app after selecting the language. However, at other times when testing and switching back to other languages this prompt did not show up and the current language did not change again for some reason. I had to open/close out the app a few times before it refreshed I guess.

**Comment by inaikem** [comment]
Related to https://github.com/Automattic/wp-calypso/issues/90081

Changing the primary language to an EN variant (EN UK) and rebooting fixed the issue for me. I was seeing Studio in Traditional Chinese.

**Comment by nguyenquanghoang** [comment]
I found @derekblank "[**Add Language Switcher**](https://github.com/Automattic/studio/pull/72)" #72 solution to be perfect for solving this problem, Not only with Mac OS but also Windows. This helps to avoid switching the operating system language and can be selected right from Studio.
@wojtekn @fluiddot @stevehenty
