### ISSUE TITLE
Areas that enable dragging are not clearly defined in the main app window

### ISSUE THREAD

**Issue by zdenys** [Automattic/studio#29]
### Quick summary

It's unclear which areas can be clicked to drag the entire app window. The narrow black frame on top, right, and bottom seems to be one area. But then on the left sidebar it's really unclear what part can be clicked to enable the dragging. The white area doesn't enable dragging at all.

https://github.com/Automattic/studio/assets/39308239/d3f60f2e-2825-46e8-b6bb-4fd75f1938c8

### Steps to reproduce

Try clicking various black and white part areas of the app main window to be surprised which ones enable dragging and which ones don't.

### What you expected to happen

Enable dragging by clicking any empty area of the main app screen.

### What actually happened

It's unclear which areas can be clicked to drag the entire app window.

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform

Mac Silicon

### Logs or notes

This is similar to:

- https://github.com/Automattic/studio/issues/28

**Comment by wojtekn** [comment]
Thanks for reporting that @zdenys . We are going to improve drag triggers to make them consistent across the Studio and other apps.

**Comment by SiobhyB** [comment]
Addressed as part of https://github.com/Automattic/studio/pull/75, feel welcome to re-open if there's anything that needs further iteration!
