### ISSUE TITLE
Settings screen: false label

### ISSUE THREAD

**Issue by TRILOS** [Automattic/studio#304]
### Quick summary

On the settings screen, the label for displaying the current set php version, the label shows "WP-Version:" instead of "php version".

### Steps to reproduce

Click on Settings screen

### What you expected to happen

correct label

### What actually happened

false label

### Impact

All

### Available workarounds?

No but the app is still usable

### Platform

Windows

### Logs or notes

Studio 1.4 on Winows 10

**Comment by matt-west** [comment]
Thanks for reporting @TRILOS.

@wojtekn This was a bad translation. I’ve fixed it through translate.wordpress.com.

**Comment by wojtekn** [comment]
Thanks @matt-west , good catch. I see it happened for the German translation.

I will close the issue, and this change will be included in the next release.
