### ISSUE TITLE
Unknown database settings block common ways for site import

### ISSUE THREAD

**Issue by TRILOS** [Automattic/studio#310]
### Quick summary

Please enhance Studio Settings tab with Database Host, Name, User, Password.

### Steps to reproduce

Plugins like BackWPup need credentials for restoring from a backup file but these are not documented or even editable.

### What you expected to happen

All is said

### What actually happened

All is said

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform

Windows

### Logs or notes

Studio 1.4

On the one hand, this is a blocker for common uses cases.
On the other hand, this might be an unwanted feature request if Studio is dedicated to enhance paid wp.com services.
Just guessing...

**Comment by wojtekn** [comment]
> Please enhance Studio Settings tab with Database Host, Name, User, Password.

Thanks for adding the feature request. Studio doesn't currently use MySQL, so it can't show the database host, user, and password. It uses SQLite instead, and this database can be managed by other tools, e.g. sqlite3. 

However, we've just released [Studio 1.1.0](https://github.com/Automattic/studio/releases/tag/v1.1.0), which supports importing and exporting the site.
