### ISSUE TITLE
Feature Request: Access to database using Workbench MSQL

### ISSUE THREAD

**Issue by Kri8tivemike** [Automattic/studio#327]
### What

Please add a new feature that allows us to access the database

### Why

I currently have a website that I need to setup before pushing live but I can because I only have the SQL file and WP files.

**Comment by wojtekn** [comment]
@Kri8tivemike Studio uses SQLite instead of MySQL, so MySQL Workbench won't let you to manage database 

Please check https://developer.wordpress.com/docs/developer-tools/studio/#12-how-can-i-manage-the-studio-site-s-sqlite-database- for some ideas on how to manage Studio's site database.
