### ISSUE TITLE
SQLite error "SQLSTATE[HY000]: General error: 1 no such table: pragma_table_info" on PHP 7.0 and 7.1

### ISSUE THREAD

**Issue by bluefuton** [Automattic/studio#345]
### Quick summary

I really appreciate having older versions of PHP available in Studio to test plugins with.

However, when using either PHP 7.0 or 7.1, I get the following SQLite error when attempting to set up an API key in Akismet:

```
SQLSTATE[HY000]: General error: 1 no such table: pragma_table_info
```

My limited research suggests that this table may not be accessible in older versions of SQLite, and it may be required to use the format `PRAGMA table_info` instead.

### Steps to reproduce

1. Start the Studio app.
2. Install and activate the Akismet plugin.
3. Enable WP_DEBUG in your wp-config.php.
4. Go to /wp-admin/options-general.php?page=akismet-key-config
5. Enter something in the API key input and submit.

### What you expected to happen

The new API key is set up and you are shown the stats and config view.

### What actually happened

Database error prevents API key from being inserted.

Here's the full error text (I've replaced the API key with api-key-here):

```
WordPress database error: [<div style="clear:both">&nbsp;</div> <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;"> <p>MySQL query:</p> <p>INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('wordpress_api_key', 'api-key-here', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)</p> <p>Queries made or created this session were:</p> <ol> <li>Executing: BEGIN | (no parameters)</li> <li>Executing: SELECT * FROM pragma_table_info(:table_name) as l WHERE l.pk &gt; 0; | (no parameters)</li> <li>Executing: ROLLBACK | (no parameters)</li> </ol> </div> <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;"> Error occurred at line 3775 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: pragma_table_info. </div> <p>Backtrace:</p> <pre>#0 /var/www/html/wp-content/mu-plugins/sqlite-database-integration-main/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message() #1 /var/www/html/wp-includes/option.php(1006): WP_SQLite_DB->query('INSERT INTO `wp...') #2 /var/www/html/wp-includes/option.php(809): add_option('wordpress_api_k...', 'api-key-here', '', 'yes') #3 /var/www/html/wp-content/plugins/trunk/class.akismet-admin.php(332): update_option('wordpress_api_k...', 'api-key-here') #4 /var/www/html/wp-content/plugins/trunk/class.akismet-admin.php(318): Akismet_Admin::save_key('api-key-here') #5 /var/www/html/wp-content/plugins/trunk/class.akismet-admin.php(33): Akismet_Admin::enter_api_key() #6 /var/www/html/wp-includes/class-wp-hook.php(324): Akismet_Admin::init('') #7 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #8 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #9 /var/www/html/wp-settings.php(695): do_action('init') #10 /var/www/html/wp-config.php(96): require_once('/var/www/html/w...') #11 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...') #12 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #13 /var/www/html/wp-admin/options-general.php(10): require_once('/var/www/html/w...') #14 {main}</pre> ] INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('wordpress_api_key', 'api-key-here', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
```

### Impact

Some (< 50%)

### Available workarounds?

No but the app is still usable

### Platform

Mac Silicon

**Comment by wojtekn** [comment]
@bluefuton, thanks for reporting the issue.

I couldn't reproduce it on a new site added in Studio in any PHP version. Does it occur for you on newly added site? Could you please share more details on how you add and configure the site in Studio?

**Comment by bluefuton** [comment]
Thanks @wojtekn! No, I'm not able to reproduce it in a brand new site on Studio.

I notice the new site also shows 'Database: SQLite' in the wp-admin header, which wasn't on my older site:

<img width="154" alt="Screenshot 2024-07-10 at 11 17 29" src="https://github.com/Automattic/studio/assets/17325/fb2a3863-0e2f-4862-807c-146589f564fe">

I'll close the issue as it seems to be resolved with a fresh site. Thanks!
