### ISSUE TITLE
cURL PHP extension

### ISSUE THREAD

**Issue by NetPotion** [Automattic/studio#347]
### Quick summary

I am unable to use Duplicator Pro in Studio because it says cURL PHP extension is not enabled, yet I can find no place to actually enable this.

### Steps to reproduce

Add Duplicator Pro to any site created inside of Studio and attempt to activate the license. 

### What you expected to happen

I expect to be able to license this and any plugin installed.

### What actually happened

**It fails.**

**The following error will appear:**

Message: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
stream_socket_client(): Failed to enable crypto
stream_socket_client(): Unable to connect to ssl://duplicator.com:443 (Unknown error)
Error code: http_request_failed

Request Details
{
"url": "https:\/\/[duplicator.com](http://duplicator.com/)",
"curlEnabled": false,
"params": {
"timeout": 15,
"sslverify": false,
"user-agent": "WordPress\/6.5.5",
"body": {
"edd_action": "activate_license",
"license": "21cc5f5359aec1636257c5bc5fdd556f",
"item_name": "Duplicator+Pro",
"url": "http:\/\/localhost:8882"
}
}
}
Response Details
null

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Windows

**Comment by wojtekn** [comment]
Thanks for reporting the issue, @NetPotion. The team is aware of it, and it has already been reported under https://github.com/Automattic/studio/issues/181.

I will close this one as a duplicate.
