### ISSUE TITLE
curl_init required in Studio

### ISSUE THREAD

**Issue by Ulrich-Adler** [Automattic/studio#389]
### Quick summary

Most migration tools need the library cURL, and are msissing curl_init.

### Steps to reproduce

Start Studio App
Add Plugin Everest Backup or another
Restore Backup file
Plugin will stop with error message

### What you expected to happen

Provide information how library cURL can be added or update Studio to include the library cURL.

### What actually happened

Backup/Restore Plugin will stop with error message.

### Impact

Most (> 50%)

### Available workarounds?

No and the app is unusable

### Platform

Windows

### Logs or notes

none

**Comment by wojtekn** [comment]
Thanks for reporting the issue @Ulrich-Adler.

I will close it, as we have it already tracked under https://github.com/Automattic/studio/issues/181

**Comment by Ulrich-Adler** [comment]
I do not understand #181. Is there a solution? Or is a solution planned? If I cannot use a restore plugin, I cannot use Studio.

Sent from MailDroid

-----Original Message-----

**Comment by wojtekn** [comment]
@Ulrich-Adler it's not solved yet, but we are planning to look for a solution.

I closed this report to avoid having two issues reporting the same problem. Issues are linked together, so whoever works on the #181 can find this issue as a reference.
