### ISSUE TITLE
Plugins or themes that have pending updates get deleted on update

### ISSUE THREAD

**Issue by nagpai** [Automattic/studio#394]
### Quick summary

Plugins or themes, that show pending updates, get deleted if we try to update them.

### Steps to reproduce

1. Start the studio app
2. You will need a site with an older version of a plugin 
3. Try updating the plugin from within the WP Admin
4. You will see an error - `Update failed. Could not remove the old plugin`

![image](https://github.com/user-attachments/assets/5bf951b2-409c-4920-ad02-c868b3495fc1)

5. Similar errors are visible with theme updates too
6. The folder of the older version of the theme or plugin disappears too. 

### What you expected to happen

Updates should smoothly finish

### What actually happened

Error while trying to update, and older plugin gets deleted too. Leads to a database error if you try to update the SQLite plugin. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform

Mac Silicon

### Logs or notes

Browser: chrome / Vivaldi ( based on Chromium )

**Comment by wojtekn** [comment]
@nagpai thanks for your report! 

We had such issue tracked and already fixed it under https://github.com/Automattic/studio/pull/156. I just tested Akismet plugin upgrade in Studio 1.0.6, and it worked fine.

Could you provide more details about the Studio version you are using?

**Comment by wojtekn** [comment]
I've just tested it in Studio 1.1.1 and couldn't reproduce it.
