### ISSUE TITLE
Deprecation notice for strtoupper in the sqlite-database-integration must-use plugin

### ISSUE THREAD

**Issue by mrdarrengriffin** [Automattic/studio#395]
### Quick summary

The following notice appears:
```
Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-token.php on line 221
```

A null check is not performed for `$this->value` in the `sqlite-database-integration` must-use plugin causing a deprecation notice.

I am not 100% where to find the source file for this to raise a PR but the issue is on line 221 of `/wp-content/mu-plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-token.php`

![image](https://github.com/user-attachments/assets/e4cd01b1-4331-4f9a-93bd-7d3db5f794f6)

### Steps to reproduce

1. Enable WP_DEBUG via wp-config.php
2. Enter the admin area

### What you expected to happen

An appropriate null check should be used possibly above the related condition to then call the `$this->is_semantically_void()` function

### What actually happened

A deprecation notice appears at the top of every admin page

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform

Windows

### Logs or notes

This applies to all sites using PHP 8 or above (I believe)

**Comment by mrdarrengriffin** [comment]
For anyone needing to fix this, you can apply an empty fallback string within `\wp-content\mu-plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-token.php:214`

![image](https://github.com/user-attachments/assets/4c090072-8c51-429f-881b-27aa5ae3b7c7)

**Comment by wojtekn** [comment]
Thanks for the report @mrdarrengriffin.

It would make sense to report it in https://github.com/wordPress/sqlite-database-integration/, though.

**Comment by mrdarrengriffin** [comment]
Ah, thanks @wojtekn, I will raise it over there

**Comment by wojtekn** [comment]
Thanks @mrdarrengriffin!

**Comment by mrdarrengriffin** [comment]
@wojtekn, It appears to have been fixed late last week. I think it will just need updating across installs in Studio. 

Reference: https://github.com/WordPress/sqlite-database-integration/issues/54

**Comment by wojtekn** [comment]
@mrdarrengriffin I see a new plugin version was released today (https://github.com/WordPress/sqlite-database-integration/releases/tag/v2.1.12).

Studio should upgrade the plugin for your site when you stop and start it.

**Comment by mrdarrengriffin** [comment]
Fantastic. Thanks @wojtekn, have a great day!
