### ISSUE TITLE
Suggested site names are not translated

### ISSUE THREAD

**Issue by fluiddot** [Automattic/studio#416]
### Quick summary

When creating a site, the suggested site name is not translated.

### Steps to reproduce

1. Set the OS to a non-English language supported by the Studio app (e.g. Spanish).
2. Open the app.
3. Create a site.
4. In the creation site modal, observe that the suggested site name is not translated (e.g. `My Sparkly Website`).

### What you expected to happen

All strings in the app are translated.

### What actually happened

Suggested site names are not translated.

### Impact

All

### Available workarounds?

There is no user impact

### Platform

Mac Silicon, Mac Intel

**Comment by wojtekn** [comment]
Thanks for reporting it. It looks like the first website name is translated:

<img width="1012" alt="Zrzut ekranu 2024-08-2 o 09 52 40" src="https://github.com/user-attachments/assets/d26f478e-a241-4fab-9e48-978d0803ab73">

And subsequent names are not:

<img width="1012" alt="Zrzut ekranu 2024-08-2 o 09 52 54" src="https://github.com/user-attachments/assets/bdd9d979-0f63-4e02-a3a5-98d61fed15f5">

Phrases are translated in GlotPress.

**Comment by katinthehatsite** [comment]
We would need to be careful with translating those as in some languages that don't use Latin characters, this might cause issues. See: https://github.com/Automattic/dotcom-forge/issues/8648
