### ISSUE TITLE
Feature Request: Add backup/snapshot support

### ISSUE THREAD

**Issue by andrewjmead** [Automattic/studio#43]
### What

I would like to see an option to create backups and restore them.

### Why

This would keep me organized and allow me to try out new ideas without being worried about losing work.

**Comment by faisalahammad** [comment]
That would be great to have a site **Export/Import** option. +1

**Comment by markhowellsmead** [comment]
I agree; this would be particularly useful when migrating a project between two development machines running Studio. (Export from one and import to the other.)

**Comment by wojtekn** [comment]
We've just released [Studio 1.1.0](https://github.com/Automattic/studio/releases/tag/v1.1.0), which supports exporting and importing the site. 

This can be used as a backup tool as well. Let us know if it works for you! 🙂

**Comment by andrewjmead** [comment]
Amazing! Thanks for this 🥳
