### ISSUE TITLE
Overview Tab: Three-column layout makes button text difficult to understand in certain languages

### ISSUE THREAD

**Issue by t-hamano** [Automattic/studio#46]
### Quick summary

The Overview tab has two sections, a and b, and the buttons are laid out in a 3-column layout. And the overflowed text will be hidden.

Since the width of the text varies depending on the language, it may be difficult to understand what the button means. Of course, the full text will be displayed via a tooltip if you focus on the button, but I suggest changing to a two-column layout.

### Steps to reproduce

Just launch the Studio.

### What you expected to happen

All text is fully displayed.

![two-columns](https://github.com/Automattic/studio/assets/54422211/958a18fb-3b65-4535-ba4e-b45e2698613d)

### What actually happened

It may not be immediately obvious what the button means because only about half of the full text is visible.

![image](https://github.com/Automattic/studio/assets/54422211/0a9e40a6-2f10-4520-9122-fd791abaf7e8)

In Japanese environments, the button text is abbreviated as follows:

- Site Editor: サイトエディター > サイトエ...
- Navigation: ナビゲーション > ナビゲー...
- Templates: テンプレート > テンプレ...
- File explorer: エクスプローラー > エクスプ...

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Windows

**Comment by wojtekn** [comment]
Thanks for feedback @t-hamano !

@matt-west Would it make sense to display two buttons in a row as proposed above and three when the window is wider?

**Comment by matt-west** [comment]
Thanks for reporting this @t-hamano.

> Would it make sense to display two buttons in a row as proposed above and three when the window is wider?

That could work. I’d like to do a bit more design exploration on this though. Leave it with me.

**Comment by matt-west** [comment]
I explored a few different layout options for the quick actions to better accommodate languages with longer strings.

![Image](https://github.com/Automattic/studio/assets/417538/adb577e7-f52f-413c-89b9-741345b7749b)

I think the two-column layout (top left) that @t-hamano proposed is working best. 

![Image](https://github.com/Automattic/studio/assets/417538/4c0697e7-bd0e-48f0-a9ad-a061cdd48079)

Once window reaches `1040px` wide, we should switch to the three-column layout.

![Image](https://github.com/Automattic/studio/assets/417538/0ac67a97-15b3-4ed2-bf89-952456d5d5a8)

We should retain the existing behaviour that truncates long strings and displays a tooltip, just in case there are still translations that would not fit the button.

![Image](https://github.com/Automattic/studio/assets/417538/4a95fa7d-6f03-4400-afba-fab83a9891ec)

What do you think?

**Comment by t-hamano** [comment]
> I think the two-column layout (top left) that @t-hamano proposed is working best.

Thank you for the design suggestions! I also agree with this approach.

The only concern is that if the number of buttons increases in the future, the two-column layout will cause overflow. In that case, we might need to increase the height of the window.

**Comment by matt-west** [comment]
> The only concern is that if the number of buttons increases in the future, the two-column layout will cause overflow. In that case, we might need to increase the height of the window.

We don't have any plans to add more buttons here at the moment, but definitely something we can keep an eye on.
