### ISSUE TITLE
Feature Request: How can I update translation using Glotpress?

### ISSUE THREAD

**Issue by Mahjouba91** [Automattic/studio#490]
### What

Hello,

By digging a bit in the repo I found that you mentioned using Glotpress to translate languages of Studio.

I came across a few errors in french translation so I wanted to fix it. But I can't find how to translate with Glotpress a project that is not a WordPress plugin or theme.

And I couldn't find any info on the doc about it?

### Why

It will be easier for contributors to improve languages or add new ones.

### How

New documentation

**Comment by wojtekn** [comment]
Hi @Mahjouba91 ! We have https://github.com/Automattic/studio/blob/trunk/docs/localization.md. Does it help you?

**Comment by Mahjouba91** [comment]
Yes sorry I missed that, thank you
