### ISSUE TITLE
Feature Request: allow embedding audio and video 

### ISSUE THREAD

**Issue by rinazrina** [Automattic/studio#54]
### What

Please allow audio and video embeds. At the moment, embedding an audio or video from services such as Soundcloud and YouTube is not allowed. I got an error, `Sorry, this content could not be embedded.` 

![Screenshot on 2024-04-28 at 16-03-43](https://github.com/Automattic/studio/assets/33721365/f46ba071-377c-43e7-b56d-c419cabbdef5)

### Why

This will allow us to conveniently display demo content by embedding rather than uploading.

User request: 8112852-zd-a8c

**Comment by wojtekn** [comment]
Thanks for reporting that issue @rinazrina. We reproduced it, and will check how we can improve it.

**Comment by wojtekn** [comment]
It's fixed now: https://github.com/Automattic/studio/releases/tag/v1.0.2
