### ISSUE TITLE
Feature Request: Add Copy Short

### ISSUE THREAD

**Issue by menjilx** [Automattic/studio#56]
### What

Is adding a "copy" button beside the demo link possible?
<img width="365" alt="image" src="https://github.com/Automattic/studio/assets/14908836/fb4ccb8d-aaf4-47a0-a1a2-a2454c405fd3">

### Why

It will give us the freedom to copy and not need to click the demo link to copy.

**Comment by derekblank** [comment]
Addressed in https://github.com/Automattic/studio/pull/57. Thanks for the suggestion @menjilx.
