### ISSUE TITLE
Studio: Local path note missing padding during onboarding

### ISSUE THREAD

**Issue by matt-west** [Automattic/studio#617]
### Quick summary

![Image](https://github.com/user-attachments/assets/ba484a98-015b-4ef6-a796-9f01bda46a8e)

### Steps to reproduce

1. Delete all Studio sites
2. Open the **Advanced settings** toggle on the onboarding screen

### What you expected to happen

The Local path field should have padding between the input and the hint text.

### What actually happened

There’s no padding.

### Impact

All

### Available workarounds?

No but the app is still usable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Studio for Mac - Replicated

📌 ACTIONS
- Triaged
