### ISSUE TITLE
Studio: Remove border from file inputs

### ISSUE THREAD

**Issue by matt-west** [Automattic/studio#618]
### Quick summary

![Image](https://github.com/user-attachments/assets/22ae04e8-3695-4178-b5af-0acf685d5551)

### Steps to reproduce

1. Start Studio with no sites.
2. Note that the backup and local path fields have a border to the left of the icon.

### What you expected to happen

Remove the border.

### What actually happened

The border is still present from an older version of the design.

### Impact

All

### Available workarounds?

No but the app is still usable

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Studio for Mac - Replicated

📌 ACTIONS
- Triaged
