### ISSUE TITLE
Feature Request: change site url

### ISSUE THREAD

**Issue by jeffpaul** [Automattic/studio#638]
### What

In using Studio to demo new sites/apps/plugins/etc to folks, it would be great to be able to easily adjust the domain/site URL within Studio (e.g. client-name-test.local).

### Why

This presents better when taking screenshots/screencasts or live demoing when the domain can represent the context of what's being shown off versus "localhost:8888".

**Comment by wojtekn** [comment]
Thanks for adding the feature request, @jeffpaul .

There is also another similar one: https://github.com/Automattic/studio/issues/215

**Comment by jeffpaul** [comment]
Closing this as a dupe, thanks!
