### ISSUE TITLE
Feature Request: Minimize to SysTray

### ISSUE THREAD

**Issue by EduardoVolpi** [Automattic/studio#750]
### What

Minimize to system tray possibility.

### Why

For a better workflow where we have switch windows and the main program windows won't get in the way.

**Comment by wojtekn** [comment]
Thanks for adding a feature request @EduardoVolpi .

We have it already tracked under https://github.com/Automattic/studio/issues/219

I will close this one, then. Feel free to add more details on how would you use the feature there.
